# Generated by Django 5.0.6 on 2024-06-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0002_rename_bookingdata_booking_bookingdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItems',
        ),
    ]
