# Generated by Django 5.0.6 on 2024-06-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0003_rename_menu_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
    ]
