# Generated by Django 5.0.6 on 2024-06-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0004_alter_menuitems_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
